import { Market } from './types';

export const MARKETS: Market[] = [
  {
    id: '4',
    type: 'binary',
    category: 'PumpFun',
    question: 'PumpFun airdrop by end of March?',
    yesPercent: 62,
    noPercent: 38,
    totalBet: '$540k',
    comments: 9999,
    expiresAt: '2026-03-31',
    image: '/airdrop.png',
    createdAt: '2026-03-16',
    volume: 540000,
  },
  {
    id: '2',
    type: 'multiple',
    category: 'Memes',
    question: 'Next PumpFun token to reach 100M mcap',
    options: [
      { label: 'Alchemist AI', percent: 22 },
      { label: 'jelly-my-jelly', percent: 18 },
      { label: 'The White Whale', percent: 15 },
      { label: 'Ai Ring Complex', percent: 13 },
      { label: 'WAR', percent: 11 },
      { label: 'Neet', percent: 9 },
      { label: 'Troll', percent: 7 },
      { label: 'None of the above', percent: 5 },
    ],
    totalBet: '$380k',
    comments: 8500,
    expiresAt: '2026-06-01',
    image: '/100m.png',
    createdAt: '2026-03-16',
    volume: 380000,
  },
  {
    id: '3',
    type: 'multiple',
    category: 'Memes',
    question: 'Next meme to hit 10M mcap',
    options: [
      { label: 'Punch', percent: 19 },
      { label: 'Chillhouse', percent: 16 },
      { label: 'PsyopAnime', percent: 14 },
      { label: 'Wojak', percent: 13 },
      { label: 'Afk', percent: 12 },
      { label: 'What The Dog Doing?', percent: 9 },
      { label: 'Maxxing', percent: 6 },
      { label: 'None of the above', percent: 11 },
    ],
    totalBet: '$220k',
    comments: 7200,
    expiresAt: '2026-05-01',
    image: '/10m.png',
    createdAt: '2026-03-16',
    volume: 220000,
  },
  {
    id: '11',
    type: 'binary',
    category: 'Business',
    question: 'Will Alon join Forbes Top 100 by end of 2026?',
    yesPercent: 47,
    noPercent: 53,
    totalBet: '$210k',
    comments: 512,
    expiresAt: '2026-12-31',
    image: '/alon.jpg',
    createdAt: '2026-03-16',
    volume: 210000,
  },
  {
    id: '5',
    type: 'binary',
    category: 'Crypto',
    question: 'Will $TRUMP flip $PUMP by end of March?',
    yesPercent: 34,
    noPercent: 66,
    totalBet: '$487k',
    comments: 1003,
    expiresAt: '2026-03-31',
    image: '/trump.png',
    createdAt: '2026-03-16',
    volume: 487000,
  },
  {
    id: '1',
    type: 'multiple',
    category: 'PumpFun',
    question: 'Next PumpFun hackaton winner',
    options: [
      { label: 'Until', percent: 18 },
      { label: 'Codec', percent: 12 },
      { label: 'Dexter AI', percent: 21 },
      { label: 'Juice', percent: 9 },
      { label: 'Trenches Game', percent: 14 },
      { label: 'Pumpville', percent: 8 },
      { label: 'Percolator', percent: 7 },
      { label: 'None of the above', percent: 11 },
    ],
    totalBet: '$404k',
    comments: 6800,
    expiresAt: '2026-07-01',
    image: '/hackaton.jpg',
    createdAt: '2026-03-16',
    volume: 404000,
  },
];
